### ISSUE TITLE
build path

### ISSUE THREAD

**Issue by ilsaul** [tschulte/gradle-jnlp-plugin#10]
Hi,
sorry for so many questions, but I would like to help you make a better plugin

you use tmp under build, can you set by default a better path?

I suggest build/webstart

thx

**Comment by tschulte** [comment]
Good point. When I created the plugin, I also thought about the output folder, but since the output is only meant to be a temporary folder. I settled with tmp. But you are right, build/webstart or build/jnlp might be better. But that would be a breaking change. I will have a look.

**Comment by aalmiray** [comment]
AFAIK `tmp` is used by other plugins too, for example the `maven-publish` uses it to compute the generated POM. Moving the working directory of the `jdlp` plugin to something else (I suggest `jnlp` to keep it consistent) would be good IMHO. If the `distribution` plugins is applied then consider adding a `$project-$version-webstart.zip` file generation option. :smile:

**Comment by ilsaul** [comment]
Hi,
tmp is ok in work in progress process, but output task better have a definitive path.
i.e.: java build output is under lib.
jnlp is ok for me too.
Distribution I don't use it because I copy files directly in the folder on the server, but I think your suggestion is correct.
