### ISSUE TITLE
how to add property in the resources tag

### ISSUE THREAD

**Issue by ilsaul** [tschulte/gradle-jnlp-plugin#11]
Hi,
I need to add a property to the resources tag in the jnlp
I try to use
jnlp.withXml.resources {
	property('name' : 'browser', 'value' : '6.00.2800') {}
}

but in the file I find 2 resources tag.

thanks.

**Comment by tschulte** [comment]
That's exactly how we do it in our project. There is no problem with having two resource elements in the resulting jnlp. Webstart does not have any problem with this.

**Comment by ilsaul** [comment]
Do you mean the next is correct?

  <resources>
    <property name='browser' value='6.00.2800' />
  </resources>
  <resources>
    <j2se version='6.0+' max-heap-size='1024m' min-heap-size='128m' />
    <jar href='lib/XXXXX.jar' version='1.2' />
    <property name='jnlp.versionEnabled' value='true' />
  </resources>

I'm not too sure

**Comment by tschulte** [comment]
Yes, I at least never had any issues with this. We use this at our project and have no problem accessing the system property from our application.
