### ISSUE TITLE
version missed

### ISSUE THREAD

**Issue by ilsaul** [tschulte/gradle-jnlp-plugin#12]
May I ask to add the next code:

<pre><code>
diff --git a/gradle-jnlp-plugin/src/main/groovy/de/gliderpilot/gradle/jnlp/GradleJnlpPluginExtension.groovy b/gradle-jnlp-plugin/src/main/groovy/de/gliderpilot/gradle/jnlp/GradleJnlpPluginExtension.groovy
index b4886ef..85ab6b0 100644
--- a/gradle-jnlp-plugin/src/main/groovy/de/gliderpilot/gradle/jnlp/GradleJnlpPluginExtension.groovy
+++ b/gradle-jnlp-plugin/src/main/groovy/de/gliderpilot/gradle/jnlp/GradleJnlpPluginExtension.groovy
@@ -36,8 +36,6 @@
     // not needed, if application-plugin is applied
     String mainClassName
 
-
-
     Map<String, String> jnlpParams = [spec: '7.0', href: 'launch.jnlp']
     Map<String, String> j2seParams
 
@@ -92,6 +90,10 @@ void spec(String spec) {
         jnlpParams.spec = spec
     }
 
+    void version(String version) {
+        jnlpParams.version = version
+    }
+
     void withXml(Closure closure) {
         withXmlClosure = closure
     }
</code></pre>

**Comment by ilsaul** [comment]
I can use project version sorry close this. No need to change,

**Comment by tschulte** [comment]
Yes, the default is to use project.version, if set. But documentation is on my TODO list;)
