### ISSUE TITLE
Don't append alias to signed jar?

### ISSUE THREAD

**Issue by totszwai** [tschulte/gradle-jnlp-plugin#51]
Is there a way to not append the alias to the signed jar??

    jnlp {
        useVersions = false
        ...
    }

Still puts the alias at the end of the signed jar. Is there a point to append it even?

**Comment by tschulte** [comment]
Sorry for the late reply. Please see #22 and https://github.com/tschulte/gradle-jnlp-plugin/releases/tag/v1.0.0

To not append the alias to the end of the jars, just configure

```
jnlp {
    jnlp.versionAppendix = { "" }
}
```
