### ISSUE TITLE
Rename launch.jnlp

### ISSUE THREAD

**Issue by ilsaul** [tschulte/gradle-jnlp-plugin#8]
Hi,
can give a name to the jnlp?

**Comment by tschulte** [comment]
Currently this is not supported directly. But you can do it like this

tasks.generateJnlp {
    output new File(project.buildDir, 'tmp/jnlp/start.jnlp')
}

**Comment by ilsaul** [comment]
Ok true but is not better set something directly with the name?
tasks.generateJnlp.destinationName = 'start'
I don't know if syntax is correct.

**Comment by ilsaul** [comment]
I think if I set:
jnlp {
	href 'foo.jnlp'
}

I just have the name and the task need only to use it.

**Comment by ilsaul** [comment]
I try to make a change of the project tell me if you like it. If you like can you add to your project.

<pre><code>
diff --git a/gradle-jnlp-plugin/src/main/groovy/de/gliderpilot/gradle/jnlp/GradleJnlpPlugin.groovy b/gradle-jnlp-plugin/src/main/groovy/de/gliderpilot/gradle/jnlp/GradleJnlpPlugin.groovy
index dacda45..8fb144c 100644
--- a/gradle-jnlp-plugin/src/main/groovy/de/gliderpilot/gradle/jnlp/GradleJnlpPlugin.groovy
+++ b/gradle-jnlp-plugin/src/main/groovy/de/gliderpilot/gradle/jnlp/GradleJnlpPlugin.groovy
@@ -22,6 +22,9 @@
  * This is the main plugin file. Put a description of your plugin here.
  */
 class GradleJnlpPlugin implements Plugin<Project> {
+
+    String destinationPath = 'jnlp'
+
     void apply(Project project) {
         project.extensions.create('jnlp', GradleJnlpPluginExtension, this, project)
 
@@ -29,21 +32,22 @@ void apply(Project project) {
 
         project.tasks.create('generateJnlp', JnlpTask) {
             from = project.configurations.jnlp
-            output new File(project.buildDir, 'tmp/jnlp/launch.jnlp')
+            output new File(project.buildDir, destinationPath + '/launch.jnlp')
+            //output null
         }
         project.tasks.create('copyJars', CopyJarsTask) {
             onlyIf { !project.jnlp.signJarParams }
             from = project.configurations.jnlp
-            into new File(project.buildDir, 'tmp/jnlp/lib')
+            into new File(project.buildDir, destinationPath + '/lib')
         }
         project.tasks.create('signJars', SignJarsTask) {
             onlyIf { project.jnlp.signJarParams }
             from = project.configurations.jnlp
-            into new File(project.buildDir, 'tmp/jnlp/lib')
+            into new File(project.buildDir, destinationPath + '/lib')
         }
         project.tasks.create('createWebstartDir') {
             dependsOn 'generateJnlp', 'copyJars', 'signJars'
-            outputs.dir new File(project.buildDir, 'tmp/jnlp')
+            outputs.dir new File(project.buildDir, destinationPath)
         }
         project.plugins.withId('java') {
             // if plugin java is applied use the runtime configuration
diff --git a/gradle-jnlp-plugin/src/main/groovy/de/gliderpilot/gradle/jnlp/JnlpTask.groovy b/gradle-jnlp-plugin/src/main/groovy/de/gliderpilot/gradle/jnlp/JnlpTask.groovy
index 597ef6b..e92ce7e 100644
--- a/gradle-jnlp-plugin/src/main/groovy/de/gliderpilot/gradle/jnlp/JnlpTask.groovy
+++ b/gradle-jnlp-plugin/src/main/groovy/de/gliderpilot/gradle/jnlp/JnlpTask.groovy
@@ -36,6 +36,7 @@
 
     @TaskAction
     void generateJnlp() {
+        if (project.jnlp.jnlpParams.href != null) output = new File(output.parent, project.jnlp.jnlpParams.href)
         MarkupBuilder xml = new MarkupBuilder(output.newPrintWriter('UTF-8'))
         xml.mkp.xmlDeclaration(version:'1.0', encoding: 'UTF-8')
         xml.jnlp(project.jnlp.jnlpParams) {
</code></pre>

**Comment by tschulte** [comment]
This would be no problem to implement. I will have a look.

**Comment by tschulte** [comment]
Can you open a pull request for your proposed changes. Than I can comment on the pull request.

- I would put destinationPath to the extension.
- When using JNLPDownloadServlet one might set href to $$name

**Comment by ilsaul** [comment]
I created the pull request with my changes, do whatever you want with that
